version: 0.2

phases:
  build:
    commands:
      - cd terraform/production
      - terraform init -backend-config="bucket=$TFSTATE_BUCKET"
      - terraform destroy -var tfstate_bucket=$TFSTATE_BUCKET -auto-approve
