version: 0.2

phases:
  build:
    commands:
      - cd terraform/staging
      - terraform init -backend-config="bucket=$TFSTATE_BUCKET"
      - terraform apply -var tfstate_bucket=$TFSTATE_BUCKET -auto-approve
