version: 0.2

phases:
  build:
    commands:
      - cd terraform/qa
      - terraform init -backend-config="bucket=$TFSTATE_BUCKET"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform apply -var tfstate_bucket=$TFSTATE_BUCKET -auto-approve
